export const linkLocation = {
    'Documents': 'https://www.baidu.com/',
    'Ec³ cube': 'https://www.baidu.com/',
    'Staking': 'https://stake.ec-cube.io/',
    'Discord': 'https://www.baidu.com/',
    'X': 'https://twitter.com/Ec3_DeEnergy',
    'Telegram': 'https://t.me/Ec3_DeEnergy',
    'support@Ec-3.io': 'mailto:support@x-fluid.com',

    'Download Ec³ App': 'https://www.baidu.com/',
    'Shopping Car': 'https://www.baidu.com/',
    'Developers': 'https://www.baidu.com/',
    'Mine': 'https://www.baidu.com/',
    'Tokenomic': 'https://www.baidu.com/',
    'FAQs': 'https://www.baidu.com/',
    'Product User Guide': 'https://www.baidu.com/',
    'X': 'https://twitter.com/Ec3_DeEnergy',
    'Discord': 'https://discord.gg/kaA5A88Z8X',
    'Medium': 'https://medium.com/@ec3.deenergy',
    'Telegram': 'https://t.me/Ec3_DeEnergy',
}
